plugins:
    -   path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
        spec: "@yarnpkg/plugin-interactive-tools"

packageExtensions:
    "bootstrap@*":
        dependencies:
            "@popperjs/core": "*"


yarnPath: .yarn/releases/yarn-3.5.1.cjs
