name: Tests
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        types:
            - opened
            - synchronize
            - ready_for_review

jobs:
    functional-smoke-e2e-tests:
        name: Functional, smoke and E2E tests
        runs-on: ubuntu-latest
        if: >-
            github.event_name == 'push' || 
            (github.event_name == 'pull_request' && !github.event.pull_request.draft)
        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: api_platform_demo_test
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        strategy:
            fail-fast: true

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP with tools
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.2
                    coverage: pcov
                    tools: composer:v2, php-cs-fixer

            -   name: Copy .env.ci to .env.local
                run: cp .env.ci .env.local

            -   name: Get composer cache directory
                id: composer-cache
                run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            -   name: Cache composer dependencies
                uses: actions/cache@v3
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-

            -   name: Install Composer dependencies
                run: composer install --no-interaction --no-progress

            -   name: Create .env.local.php for test environment
                run: composer dump-env test

            -   name: Debug .env.local.php
                run: cat .env.local.php

            -   name: Clear cache
                run: php bin/console cache:clear -vvv

            -   name: Debug .env files
                run: php bin/console debug:dotenv

            -   name: Show about information
                run: php bin/console about

            -   name: Create MySQL database
                run: php bin/console doctrine:database:create --if-not-exists

            -   name: Execute migrations
                run: php bin/console doctrine:migrations:migrate

            -   name: Run functional tests
                run: vendor/bin/phpunit --group functional

            -   name: Run smoke tests
                run: vendor/bin/phpunit --group smoke

            -   name: Run e2e tests
                run: vendor/bin/phpunit --group e2e
